# Generated by Django 5.2.9 on 2026-01-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('Social', 'Social'), ('Romantic', 'Romantic'), ('Spiritual', 'Spiritual'), ('Professional', 'Professional')], max_length=50)),
                ('confidence', models.FloatField()),
                ('emotional_warmth', models.FloatField()),
                ('romantic_language', models.FloatField()),
                ('spiritual_reference', models.FloatField()),
                ('task_focus', models.FloatField()),
                ('formality', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
