# Generated by Django 5.2.10 on 2026-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversationsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('receiver_id', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'conversation_messages',
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='conversationsummary',
            new_name='api_convers_user_a__91a31f_idx',
            old_name='api_conversa_user_a__f7d8d3_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationsummary',
            new_name='api_convers_last_me_1ad34c_idx',
            old_name='api_conversa_last_me_4a9e27_idx',
        ),
        migrations.AlterField(
            model_name='conversationsummary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
