# Generated by Django 5.2.10 on 2026-01-10 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_conversationmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationAnalysis',
        ),
    ]
