# Generated by Django 5.2.10 on 2026-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_conversationanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.TextField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'posts_comments',
                'managed': False,
            },
        ),
    ]
